export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const SET_AUTH_REDIRECT_PATH = 'AUTH_REDIRECT_PATH'

export const PRODUCT_FETCH_START = 'PRODUCT_FETCH_START'
export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS'
export const PRODUCT_FETCH_FAIL = 'PRODUCT_FETCH_FAIL'

export const PRODUCT_DATA_FETCH_START = 'PRODUCT_DATA_FETCH_START'
export const PRODUCT_DATA_FETCH_SUCCESS = 'PRODUCT_DATA_FETCH_SUCCESS'
export const PRODUCT_DATA_FETCH_FAIL = 'PRODUCT_DATA_FETCH_FAIL'

export const PRODUCT_FETCH_START_ADMIN = 'PRODUCT_FETCH_START_ADMIN'
export const PRODUCT_FETCH_SUCCESS_ADMIN = 'PRODUCT_FETCH_SUCCESS_ADMIN'
export const PRODUCT_FETCH_FAIL_ADMIN = 'PRODUCT_FETCH_FAIL_ADMIN'



export const PRODUCT_VARIATION_FETCH_START = 'PRODUCT_VARIATION_FETCH_START'
export const PRODUCT_VARIATION_FETCH_SUCCESS = 'PRODUCT_VARIATION_FETCH_SUCCESS'
export const PRODUCT_VARIATION_FETCH_FAIL = 'PRODUCT_VARIATION_FETCH_FAIL'

export const SIGNUP_START = 'SIGNUP_START'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

export const PROFILE_FETCH_START = 'PROFILE_FETCH_START'
export const PROFILE_FETCH_FAIL = 'PROFILE_FETCH_FAIL'
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS'

export const ADDRESS_FETCH_START = 'ADDRESS_FETCH_START'
export const ADDRESS_FETCH_FAIL = 'ADDRESS_FETCH_FAIL'
export const ADDRESS_FETCH_SUCCESS = 'ADDRESS_FETCH_SUCCESS'

export const CUSTOMER_FETCH_START = 'CUSTOMER_FETCH_START'
export const CUSTOMER_FETCH_FAIL = 'CUSTOMER_FETCH_FAIL'
export const CUSTOMER_FETCH_SUCCESS = 'CUSTOMER_FETCH_SUCCESS'

export const SELLER_FETCH_START = 'SELLER_FETCH_START'
export const SELLER_FETCH_FAIL = 'SELLER_FETCH_FAIL'
export const SELLER_FETCH_SUCCESS = 'SELLER_FETCH_SUCCESS'

export const METADATA_FIELD_POST_START = 'METADATA_FIELD_POST_START'
export const METADATA_FIELD_POST_FAIL = 'METADATA_FIELD_POST_FAIL'
export const METADATA_FIELD_POST_SUCCESS = 'METADATA_FIELD_POST_SUCCESS'

export const METADATA_FIELD_VALUE_POST_START = 'METADATA_FIELD_POST_START'
export const METADATA_FIELD_VALUE_POST_FAIL = 'METADATA_FIELD_POST_FAIL'
export const METADATA_FIELD_VALUE_POST_SUCCESS = 'METADATA_FIELD_POST_SUCCESS'

export const METADATA_FIELD_FETCH_START = 'METADATA_FIELD_FETCH_START'
export const METADATA_FIELD_FETCH_FAIL = 'METADATA_FIELD_FETCH_FAIL'
export const METADATA_FIELD_FETCH_SUCCESS = 'METADATA_FIELD_FETCH_SUCCESS'

export const CATEGORY_POST_START = 'CATEGORY_POST_START'
export const CATEGORY_POST_FAIL = 'CATEGORY_POST_FAIL'
export const CATEGORY_POST_SUCCESS = 'CATEGORY_POST_SUCCESS'


export const CATEGORY_UPDATE_START = 'CATEGORY_UPDATE_START'
export const CATEGORY_UPDATE_FAIL = 'CATEGORY_UPDATE_FAIL'
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS'

export const CATEGORY_FETCH_START = 'CATEGORY_FETCH_START'
export const CATEGORY_FETCH_FAIL = 'CATEGORY_FETCH_FAIL'
export const CATEGORY_FETCH_SUCCESS = 'CATEGORY_FETCH_SUCCESS'

export const CATEGORY_FETCH_BY_ID_START = 'CATEGORY_FETCH_BY_ID_START'
export const CATEGORY_FETCH_BY_ID_FAIL = 'CATEGORY_FETCH_BY_ID_FAIL'
export const CATEGORY_FETCH_BY_ID_SUCCESS = 'CATEGORY_FETCH_BY_ID_SUCCESS'

export const UPDATE_START = 'UPDATE_START'
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS'
export const UPDATE_FAIL = 'UPDATE_FAIL'

export const PRODUCT_POST_START = 'PRODUCT_POST_START'
export const PRODUCT_POST_FAIL = 'PRODUCT_POST_FAIL'
export const PRODUCT_POST_SUCCESS = 'PRODUCT_POST_SUCCESS'

export const DELETE_PRODUCT_START = 'DELETE_PRODUCT_START'
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'

export const SIMILAR_PRODUCT_START = 'SIMILAR_PRODUCT_START'
export const SIMILAR_PRODUCT_FAIL = 'SIMILAR_PRODUCT_FAIL'
export const SIMILAR_PRODUCT_SUCCESS = 'SIMILAR_PRODUCT_SUCCESS'

export const CATEGORY_DETAIL_FETCH_START = 'CATEGORY_DETAIL_FETCH_START'
export const CATEGORY_DETAIL_FETCH_FAIL = 'CATEGORY_DETAIL_FETCH_FAIL'
export const CATEGORY_DETAIL_FETCH_SUCCESS = 'CATEGORY_DETAIL_FETCH_SUCCESS'


export const SUB_FETCH_START = 'SUB_FETCH_START'
export const SUB_FETCH_SUCCESS = 'SUB_FETCH_SUCCESS'
export const SUB_FETCH_FAIL = 'SUB_FETCH_FAIL'

export const ACTIVATE_START = 'ACTIVATE_START'
export const ACTIVATE_SUCCESS = 'ACTIVATE_SUCCESS'
export const ACTIVATE_FAIL = 'ACTIVATE_FAIL'

export const SELLER_PRODUCT_START = 'SELLER_PRODUCT_START'
export const SELLER_PRODUCT_SUCCESS = 'SELLER_PRODUCT_SUCCESS'
export const SELLER_PRODUCT_FAIL = 'SELLER_PRODUCT_FAIL'

export const SET_LABEL = 'SET_LABEL'

export const APPLY_LOGOUT_START = 'APPLY_LOGOUT_START'
export const APPLY_LOGOUT_SUCCESS = 'APPLY_LOGOUT_SUCCESS'
export const APPLY_LOGOUT_FAIL = 'APPLY_LOGOUT_FAIL'

export const SELLER_PROFILE_FETCH_START = 'SELLER_PROFILE_FETCH_START'
export const SELLER_PROFILE_FETCH_FAIL = 'SELLER_PROFILE_FETCH_FAIL'
export const SELLER_PROFILE_FETCH_SUCCESS = 'SELLER_PROFILE_FETCH_SUCCESS'


// export const CAT_FETCH_START = 'CAT_FETCH_START'
// export const CAT_FETCH_FAIL = 'CAT_FETCH_FAIL'
// export const CAT_FETCH_SUCCESS = 'CAT_FETCH_SUCCESS'

